(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.BarbellDivaDecisionRules=api;})(typeof globalThis!=="undefined"?globalThis:window,function(){
  "use strict";
  const VERSION="23.0.0",list=v=>Array.isArray(v)?v:[],norm=v=>String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[_-]+/g," ").trim();
  const decision=(data)=>({priority:"media",severity:"info",confidence:"media",dataUsed:[],suggestion:"",conditions:[],effects:[],...data});
  const RULES=[
    {id:"safety.active-limitations",category:"safety",dependencies:["limitations","programming","exercise-knowledge"],evaluate(c){const athlete=c.context.athlete||{},active=[...list(athlete.pains),...list(athlete.motorLimitations)].filter(x=>x.status!=="risolto");if(!active.length)return[];return[decision({category:"limitations",priority:"massima",severity:"warning",confidence:"alta",title:"Limitazioni attive prima dell'ottimizzazione",rationale:`${active.length} segnalazioni attive hanno precedenza su volume e intensità.`,suggestion:"Verifica tolleranza, pattern aggravanti e alternative prima di aumentare lo stimolo.",dataUsed:active.map(x=>({label:x.area||x.movement,value:x.status,source:"athlete"})),conditions:[{expression:"activeLimitations > 0",value:true}],effects:[{axis:"training-load",target:"athlete",direction:-1}]})];}},
    {id:"recovery.deload-convergence",category:"recovery",dependencies:["history","performance","nutrition","strategy"],evaluate(c){if(c.analysis.deload?.decision!=="recommended")return[];return[decision({category:"deload",priority:"alta",severity:"warning",confidence:c.analysis.deload.confidence,title:"Segnali convergenti: deload da valutare",rationale:c.analysis.deload.reason,suggestion:"Riduci temporaneamente volume e/o intensità mantenendo la specificità tecnica.",dataUsed:list(c.analysis.deload.signals).map(x=>({label:x.key,value:x.label,source:x.source})),conditions:[{expression:"deload.decision === recommended",value:true}],effects:[{axis:"volume",target:"program",direction:-1},{axis:"intensity",target:"program",direction:-1}]})];}},
    {id:"nutrition.cut-fatigue",category:"nutrition",dependencies:["nutrition","performance","history"],evaluate(c){const phase=norm(c.context.nutrition?.phase),bad=c.analysis.deload?.signals?.length>=2;if(!["cut","mini cut"].includes(phase)||!bad)return[];return[decision({category:"fatigue",priority:"alta",severity:"warning",confidence:"alta",title:"Cut e recupero sfavorevole",rationale:`La fase ${c.context.nutrition.phase} coincide con almeno due segnali di fatica o performance.`,suggestion:"Proteggi la performance: evita aumenti di volume finché i segnali non migliorano.",dataUsed:[{label:"Fase nutrizionale",value:c.context.nutrition.phase,source:"nutrition"},{label:"Segnali",value:c.analysis.deload.signals.length,source:"calculated"}],conditions:[{expression:"nutrition in cut && fatigueSignals >= 2",value:true}],effects:[{axis:"volume",target:"program",direction:-1}]})];}},
    {id:"strategy.priority-underdosed",category:"strategy",dependencies:["athlete","strategy","programming","exercise-knowledge"],evaluate(c){return list(c.context.athlete?.muscles?.priorities).filter(x=>["alta","massima"].includes(x.level)).flatMap(item=>{const muscle=norm(item.muscle),sets=c.analysis.metrics.directSets?.[muscle]||0,freq=c.analysis.metrics.frequency?.[muscle]||0;if(sets>=6&&freq>=2)return[];return[decision({category:"strategy",priority:item.level==="massima"?"alta":"media",severity:"info",confidence:"alta",title:`Priorità ${item.muscle}: stimolo da verificare`,rationale:`Priorità ${item.level}, ${sets} serie dirette e frequenza ${freq}.`,suggestion:"Se recupero e limitazioni lo consentono, rialloca serie o frequenza verso la priorità.",dataUsed:[{label:"Priorità",value:item.level,source:"athlete"},{label:"Serie",value:sets,source:"calculated"},{label:"Frequenza",value:freq,source:"calculated"}],conditions:[{expression:"priority high && (sets < 6 || frequency < 2)",value:true}],effects:[{axis:"volume",target:muscle,direction:1}]})];});}},
    {id:"performance.stalled-progression",category:"performance",dependencies:["performance","progressions","history"],evaluate(c){return list(c.analysis.metrics?.exerciseAnalyses).filter(x=>["stalled","regression","declining"].includes(x.trend?.status)).slice(0,6).map(x=>decision({category:"exercise-performance",priority:x.trend.status==="stalled"?"alta":"massima",severity:"warning",confidence:x.trend.confidence,title:`${x.name}: ${x.trend.status==="stalled"?"stallo confermato":"regressione da approfondire"}`,rationale:`${x.trend.reason} ${x.progression.reason}`,suggestion:"Controlla recupero, prescrizione e progressione prima di aumentare il carico.",dataUsed:[{label:"Trend",value:x.trend.status,source:"calculated"},{label:"Variazione",value:x.trend.changePct,source:"calculated"},{label:"Progressione",value:x.progression.status,source:"progressions"}],conditions:[{expression:"trend in stalled|regression|declining",value:true}],effects:[{axis:"intensity",target:x.masterExerciseId||x.id,direction:-1}],actions:[{type:"openProgressions",label:"Apri progressione",sheetId:x.sheetId,exerciseId:x.id}],sheetId:x.sheetId,exerciseId:x.id}));}},
    {id:"equipment.unavailable",category:"feasibility",dependencies:["equipment","programming","exercise-knowledge"],evaluate(c){const available=new Set(list(c.context.athlete?.equipment?.items).map(norm));if(!available.size)return[];return list(c.analysis.metrics?.exercisesRaw).flatMap(ex=>{const required=list(ex.masterRecord?.equipment?.required).map(norm),missing=required.filter(x=>x&&!available.has(x));if(!missing.length)return[];return[decision({category:"equipment",priority:"alta",severity:"warning",confidence:"alta",title:`${ex.name}: attrezzatura non disponibile`,rationale:`Richiede ${missing.join(", ")}, non presente nel profilo atleta.`,suggestion:"Sostituisci con una variante compatibile della Master Exercise Library.",dataUsed:[{label:"Richiesta",value:missing.join(", "),source:"master-library"},{label:"Disponibile",value:[...available].join(", "),source:"athlete"}],conditions:[{expression:"requiredEquipment not subset of availableEquipment",value:true}],effects:[{axis:"exercise-selection",target:ex.masterExerciseId||ex.id,direction:-1}],actions:[{type:"openLibrary",label:"Apri Master Library"}],sheetId:ex.sheetId,exerciseId:ex.id})];});}}
  ];
  return{VERSION,RULES,decision};
});
