import fs from "node:fs/promises";
import vm from "node:vm";
const html=await fs.readFile(new URL("../index.html",import.meta.url),"utf8");
const appMain = await fs.readFile(new URL("../src/app-main.js", import.meta.url), "utf8");
const vmLibs = await Promise.all(["exercise-library-19.8.js","master-exercise-library.js","app-config-v144.js","athlete-context.js","coach-ai-engine-2.js","knowledge-graph.js","decision-rules.js","decision-engine.js","coach-ai3-programming.js","coach-studio.js"].map(p => fs.readFile(new URL("../" + p, import.meta.url), "utf8")));
const VM_PROLOGUE = "window.matchMedia=window.matchMedia||(q=>({matches:false,media:q,addEventListener(){},removeEventListener(){},addListener(){},removeListener(){}}));window.AudioContext=window.AudioContext||function(){};window.webkitAudioContext=window.AudioContext;window.setInterval=window.setInterval||function(){return 1};window.clearInterval=window.clearInterval||function(){};window.history=window.history||{pushState(){},replaceState(){},back(){}};window.performance=window.performance||{now:()=>Date.now(),mark(){},measure(){},getEntriesByType(){return[]}};";
const script = vmLibs.join("\n;\n") + "\n;\n" + VM_PROLOGUE + appMain.replace(/\s*const firebaseBootStarted = initFirebase\(\);[\s\S]*$/, "");
const storage=new Map(); const localStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)}; const el={addEventListener(){},querySelector(){return null;},querySelectorAll(){return[];},classList:{add(){},remove(){},toggle(){}},style:{},dataset:{}}; const document={getElementById(){return el;},querySelector(){return null;},querySelectorAll(){return[];},createElement(){return {...el};},body:el,documentElement:el,addEventListener(){}}; const context={console,structuredClone,Date,Math,JSON,Intl,Map,Set,WeakMap,Array,Object,String,Number,Boolean,RegExp,Promise,parseInt,parseFloat,isNaN,localStorage,sessionStorage:localStorage,document,navigator:{},location:{protocol:"file:",origin:"null",hash:""},URL:{createObjectURL(){return "blob:test";},revokeObjectURL(){}},Blob:class{},FileReader:class{},setTimeout(){return 1;},clearTimeout(){},requestAnimationFrame(){return 1;},addEventListener(){},removeEventListener(){},postMessage(){},window:null,globalThis:null}; context.window=context; context.globalThis=context; vm.createContext(context); new vm.Script(script).runInContext(context);
const result=vm.runInContext(`(() => { const checks=[]; const check=(name,ok)=>{checks.push({name,passed:!!ok}); if(!ok) throw new Error(name);}; const run=(names)=>{state=clone(baseState); state.programs=[]; state.training.sessions=[]; coachProgramUi.drafts.clear(); coachProgramUi.programId=""; coachProgramUi.sheetId=""; const p=programRepository.createProgram({id:"p",name:"Test",durationWeeks:8,sheets:[]},{save:false}).value; const s=programRepository.createSheet(p.id,{id:"s",code:"A",name:"Lower"},{save:false}).value; names.forEach((name,i)=>programRepository.createExercise(p.id,s.id,{id:"e"+i,name,muscle:/curl/i.test(name)?"Femorali":/extension/i.test(name)?"Quadricipiti":/abductor/i.test(name)?"Glutei":/adductor/i.test(name)?"Adduttori":"Femorali",metadata:{},prescription:{sets:3,reps:"10-15",rir:"1-2",rest:{seconds:90}}},{save:false})); coachProgramUi.programId=p.id; coachProgramUi.sheetId=s.id; return coachAiSuggestions();}; let a=run(["Leg Curl seduto","Leg Extension"]); check("Leg Curl e Leg Extension complementari",!a.some(x=>x.id==="specific-overlap")); a=run(["Leg Curl seduto","Leg Curl sdraiato"]); check("due Leg Curl valutati prudentemente",a.some(x=>x.id==="specific-overlap"&&x.involvedExercises?.length===2&&x.problem.toLowerCase().includes("potrebbero"))); a=run(["Abductor Machine","Adductor Machine"]); check("Abductor e Adductor distinti",!a.some(x=>x.id==="specific-overlap")); a=run(["RDL bilanciere","RDL manubri"]); check("RDL simili ma non assoluti",a.some(x=>x.id==="specific-overlap"&&x.confidence==="media")); return {ok:true,checks}; })()`,context); console.log(JSON.stringify(result,null,2));

