import fs from "node:fs/promises";
import vm from "node:vm";
const html = await fs.readFile(new URL("../atlas-coach-app.html", import.meta.url), "utf8");
const script = html.slice(html.lastIndexOf("<script>") + 8, html.lastIndexOf("</script>")).replace(/\s+initFirebase\(\);\s+render\(\);\s*$/, "");
const store = new Map();
const localStorage = { getItem:k=>store.get(k)??null, setItem:(k,v)=>store.set(k,String(v)), removeItem:k=>store.delete(k) };
const element = { addEventListener(){}, querySelector(){return null}, querySelectorAll(){return[]}, classList:{add(){},remove(){},toggle(){}}, style:{}, dataset:{} };
const document = { getElementById(){return element}, querySelector(){return null}, querySelectorAll(){return[]}, createElement(){return {...element}}, body:element, documentElement:element, addEventListener(){} };
const context = { console, structuredClone, Date, Math, JSON, Intl, Map, Set, WeakMap, Array, Object, String, Number, Boolean, RegExp, Promise, parseInt, parseFloat, isNaN, localStorage, sessionStorage:localStorage, document, navigator:{}, location:{protocol:"file:",origin:"null",hash:""}, URL:{createObjectURL(){return "blob:test"},revokeObjectURL(){}}, Blob:class{}, FileReader:class{}, setTimeout(){return 1}, clearTimeout(){}, requestAnimationFrame(){return 1}, addEventListener(){}, removeEventListener(){}, window:null, globalThis:null };
context.window=context; context.globalThis=context; context.sourceHtml=html; vm.createContext(context); new vm.Script(script).runInContext(context);
const result = vm.runInContext(`(() => {
  const ordered = [{id:1,date:"24/06/2026",sessionCode:"F",exercises:[]},{id:2,dateInput:"2026-07-13",sessionCode:"D",exercises:[]}];
  state.training.sessions = ordered;
  if (latestSession().sessionCode !== "D") throw new Error("ultima seduta non ordinata per data reale");
  state.training.contextMode="manual"; state.training.manualPhase="Intensificazione"; state.training.manualWeek=4; state.training.manualSessionCode="D";
  const manual = currentTrainingContext();
  if (!manual.isManual || manual.week !== 4 || manual.session.code !== "D") throw new Error("contesto manuale non applicato");
  const emptyVolume = sessionVolumeInfo({exercises:[{sets:[{kg:50,reps:null}]}]});
  if (emptyVolume.available) throw new Error("volume inventato senza ripetizioni");
  if (!sourceHtml.includes('data-screen-target="logbook"') || !sourceHtml.includes('Analisi progressi')) throw new Error("collegamenti dashboard errati");
  if (sourceHtml.includes('dashboardSummaryCard("?"')) throw new Error("icone dashboard non sostituite");
  return {ok:true, imported:state.migrations.legacyAliceLogbookImported || 0, latest:latestSession().sessionCode};
})()`, context);
console.log(JSON.stringify(result,null,2));
