import fs from "node:fs/promises";
import vm from "node:vm";
const html = await fs.readFile(new URL("../index.html", import.meta.url), "utf8");
const appMain = await fs.readFile(new URL("../src/app-main.js", import.meta.url), "utf8");
const vmLibs = await Promise.all(["exercise-library-19.8.js","master-exercise-library.js","app-config-v144.js","athlete-context.js","coach-ai-engine-2.js","knowledge-graph.js","decision-rules.js","decision-engine.js","coach-ai3-programming.js","coach-studio.js"].map(p => fs.readFile(new URL("../" + p, import.meta.url), "utf8")));
const VM_PROLOGUE = "window.matchMedia=window.matchMedia||(q=>({matches:false,media:q,addEventListener(){},removeEventListener(){},addListener(){},removeListener(){}}));window.AudioContext=window.AudioContext||function(){};window.webkitAudioContext=window.AudioContext;window.setInterval=window.setInterval||function(){return 1};window.clearInterval=window.clearInterval||function(){};window.history=window.history||{pushState(){},replaceState(){},back(){}};window.performance=window.performance||{now:()=>Date.now(),mark(){},measure(){},getEntriesByType(){return[]}};";
const appCss = await fs.readFile(new URL("../coach-studio-inline.css", import.meta.url), "utf8");
const script = vmLibs.join("\n;\n") + "\n;\n" + VM_PROLOGUE + appMain.replace(/\s*const firebaseBootStarted = initFirebase\(\);[\s\S]*$/, "");
const storage = new Map();
const localStorage = { getItem:k=>storage.get(k)??null, setItem:(k,v)=>storage.set(k,String(v)), removeItem:k=>storage.delete(k) };
const el={addEventListener(){},querySelector(){return null;},querySelectorAll(){return[];},classList:{add(){},remove(){},toggle(){}},style:{},dataset:{}};
const document={getElementById(){return el;},querySelector(){return null;},querySelectorAll(){return[];},createElement(){return {...el};},body:el,documentElement:el,addEventListener(){}};
const context={console,structuredClone,Date,Math,JSON,Intl,Map,Set,WeakMap,Array,Object,String,Number,Boolean,RegExp,Promise,parseInt,parseFloat,isNaN,localStorage,sessionStorage:localStorage,document,navigator:{},location:{protocol:"file:",origin:"null",hash:""},URL:{createObjectURL(){return "blob:test";},revokeObjectURL(){}},Blob:class{},FileReader:class{},setTimeout(){return 1;},clearTimeout(){},requestAnimationFrame(){return 1;},addEventListener(){},removeEventListener(){},postMessage(){},window:null,globalThis:null};
context.sourceHtml = html + appCss + appMain; context.window=context; context.globalThis=context; vm.createContext(context); new vm.Script(script).runInContext(context);
const result = vm.runInContext(`(() => {
  const checks=[]; const check=(name,ok)=>{checks.push({name,passed:!!ok}); if(!ok) throw new Error(name);};
  state=clone(baseState); state.programs=[]; state.training.sessions=[]; coachProgramUi.drafts.clear(); coachProgramUi.programId=""; coachProgramUi.sheetId="";
  const p=programRepository.createProgram({id:"phase9",name:"Progressione",durationWeeks:16,sheets:[]},{save:false}).value;
  const s=programRepository.createSheet(p.id,{id:"phase9-sheet",code:"A",name:"Lower"},{save:false}).value;
  const e=programRepository.createExercise(p.id,s.id,{id:"pendulum-1",name:"Pendulum Squat",muscle:"Quadricipiti",metadata:{},prescription:{sets:3,reps:"8-12",rir:"1-2",rest:{seconds:90}},progression:{weeks:Array.from({length:16},(_,i)=>({weekNumber:i+1,sets:3,reps:"8-12",rir:"1-2",rest:90}))}},{save:false}).value;
  coachProgramUi.programId=p.id; coachProgramUi.sheetId=s.id; coachProgramUi.builderView="weeks";
  const grid=coachBuilderHtml(); check("griglia dinamica S16",grid.includes("S16")&&grid.includes("coach-weeks-grid"));
  const profile=coachAiExerciseProfile({exercise:"Pendulum Squat",group:"Quadricipiti",metadata:{}}); check("Pendulum riconosciuto",profile.equipment==="macchina"&&profile.pattern==="squat-knee-dominant");
  check("metadati esclusi dai suggerimenti",!coachAiSuggestions().some(x=>x.id==="missing-metadata"));
  const panel=coachAiPanelHtml(); check("scroll interno e qualità dati",panel.includes("coach-ai-scroll-area")&&panel.includes("coach-ai-quality")&&panel.includes("Informazioni da completare"));
  check("mascotte SVG inline",sourceHtml.includes('class="diva-bot"')&&sourceHtml.includes("diva-bot-antenna")&&sourceHtml.includes("coach-ai-floating"));
  check("floating apre suggerimento",sourceHtml.includes('button.closest(".coach-ai-floating")')&&sourceHtml.includes('openCoachModal("coach-ai-confirm", { suggestion:first })'));
  check("settimana trasmessa",sourceHtml.includes("data-progression-week-number")&&sourceHtml.includes("weekNumber }"));
  check("filtri normalizzati una sola volta",!sourceHtml.includes("const suggestions = coachAiSuggestions().filter"));
  check("griglia a due livelli e celle inline",sourceHtml.includes('colspan="3"')&&sourceHtml.includes("data-week-grid-field")&&sourceHtml.includes("week-fixed-exercise"));
  return {ok:true,checks};
})()`, context);
console.log(JSON.stringify(result,null,2));
