import fs from "node:fs/promises";
import vm from "node:vm";

const html = await fs.readFile(new URL("../index.html", import.meta.url), "utf8");
const start = html.lastIndexOf("<script>") + "<script>".length;
const end = html.lastIndexOf("</script>");
const applicationScript = html.slice(start, end).replace(/\s+initFirebase\(\);\s+render\(\);\s*$/, "");
const storage = new Map();
const localStorage = { getItem: (key) => storage.get(key) ?? null, setItem: (key, value) => storage.set(key, String(value)), removeItem: (key) => storage.delete(key) };
const element = { addEventListener() {}, querySelector() { return null; }, querySelectorAll() { return []; }, classList: { add() {}, remove() {}, toggle() {} }, style: {}, dataset: {} };
const document = { getElementById() { return element; }, querySelector() { return null; }, querySelectorAll() { return []; }, createElement() { return { ...element }; }, body: element, documentElement: element, addEventListener() {} };
const context = { console, structuredClone, Date, Math, JSON, Intl, Map, Set, WeakMap, Array, Object, String, Number, Boolean, RegExp, Promise, parseInt, parseFloat, isNaN, localStorage, sessionStorage: localStorage, document, navigator: {}, location: { protocol: "file:", origin: "null", hash: "" }, URL: { createObjectURL() { return "blob:test"; }, revokeObjectURL() {} }, Blob: class {}, FileReader: class {}, setTimeout() { return 1; }, clearTimeout() {}, requestAnimationFrame() { return 1; }, addEventListener() {}, removeEventListener() {}, postMessage() {}, window: null, globalThis: null };
context.window = context;
context.globalThis = context;
vm.createContext(context);
new vm.Script(applicationScript, { filename: "atlas-phase4.js" }).runInContext(context);

const result = vm.runInContext(`(() => {
  state = clone(baseState); state.programs = []; state.training.sessions = []; state.training.history = [{ id: "log-intatto" }]; state.profile.mode = "coach";
  coachProgramUi.programId = ""; coachProgramUi.sheetId = ""; coachProgramUi.drafts.clear(); coachProgramUi.dirtySheets.clear(); coachProgramUi.histories.clear(); coachProgramUi.selectedExercises.clear();
  const assertions = []; const check = (name, condition) => { assertions.push({ name, passed: !!condition }); if (!condition) throw new Error("Test fallito: " + name); };
  const program = programRepository.createProgram({ id: "p4", name: "Fase 4", durationWeeks: 8, sheets: [] }, { save: false }).value;
  const sheetA = programRepository.createSheet(program.id, { id: "p4-a", code: "A", name: "Scheda A" }, { save: false }).value;
  const sheetB = programRepository.createSheet(program.id, { id: "p4-b", code: "B", name: "Scheda B" }, { save: false }).value;
  coachProgramUi.programId = program.id; coachProgramUi.sheetId = sheetA.id;
  const created = programRepository.createExercise(program.id, sheetA.id, { id: "ex-main", name: "Military press", muscle: "Spalle", prescription: { sets: 3, reps: "8-10", rir: "1-2", rest: { seconds: 120 }, tempo: "3-1-X-0", technique: { type: "top-set" }, prescribedLoad: { value: 40, unit: "kg" } }, metadata: { equipment: "Bilanciere", pattern: "Spinta verticale", secondaryMuscles: ["Tricipiti"], mainLift: true } }, { save: false });
  check("creazione esercizio strutturato", created.ok);
  const ex = created.value;
  check("serie separate", ex.prescription.sets === 3);
  check("reps range", ex.prescription.reps.min === 8 && ex.prescription.reps.max === 10);
  check("RIR range", ex.prescription.rir.min === 1 && ex.prescription.rir.max === 2);
  check("recupero in secondi", ex.prescription.rest.seconds === 120);
  check("tempo quattro fasi", ex.prescription.tempo.valid && ex.prescription.tempo.phases.length === 4);
  check("tecnica strutturata", ex.prescription.technique.type === "top-set");
  check("carico prescritto distinto", ex.prescription.prescribedLoad.value === 40 && ex.prescription.prescribedLoad.unit === "kg");
  check("metadati libreria", ex.metadata.equipment === "Bilanciere" && ex.metadata.mainLift);
  check("reps sequenza", parseReps("10/8/6").sequence.join(",") === "10,8,6");
  check("reps AMRAP legacy", parseReps("AMRAP").label === "AMRAP");
  check("RPE alternativo", parseRir("8").min === 8);
  check("tempo legacy conservato", !parseTempo("eccentrica lenta").valid && parseTempo("eccentrica lenta").label === "eccentrica lenta");
  const draft = activeCoachBuilder(); const row = draft.rows.find((item) => item.id === ex.id); row.sets = 4; row.reps = "6/6/AMRAP"; row.effort = "RPE 8"; row.restSeconds = 180; row.technique = "rest-pause"; row.loadValue = 42.5; markCoachDraftDirty(undefined, row.id);
  check("salvataggio inline", commitActiveCoachDraft({ immediate: true, quiet: true }));
  const inline = programRepository.getExerciseById(program.id, sheetA.id, ex.id);
  check("inline canonico", inline.prescription.sets === 4 && inline.prescription.rpe.min === 8 && inline.prescription.rest.seconds === 180 && inline.prescription.technique.type === "rest-pause" && inline.prescription.prescribedLoad.value === 42.5);
  const copied = programRepository.copyExercise(program.id, sheetA.id, ex.id, program.id, sheetB.id, { position: 0, resetLoad: true, save: false });
  check("copia nuovo ID", copied.ok && copied.value.id !== ex.id && copied.value.prescription.prescribedLoad.value === null);
  const duplicate = programRepository.duplicateExercise(program.id, sheetA.id, ex.id, { save: false });
  check("duplicazione nuovo ID", duplicate.ok && duplicate.value.id !== ex.id);
  const moved = programRepository.moveExercise(program.id, sheetA.id, duplicate.value.id, program.id, sheetB.id, { position: 1, save: false });
  check("spostamento preserva ID", moved.ok && moved.value.id === duplicate.value.id && !programRepository.getExerciseById(program.id, sheetA.id, duplicate.value.id));
  const locked = programRepository.updateExercise(program.id, sheetA.id, ex.id, { metadata: { ...inline.metadata, locked: true } }, { save: false, forceLocked: true }).value;
  check("blocco protegge modifica", !programRepository.updateExercise(program.id, sheetA.id, ex.id, { name: "No" }, { save: false }).ok && locked.metadata.locked);
  const ids = programRepository.getExercises(program.id, sheetB.id).map((item) => item.id).reverse();
  check("riordino persistente", programRepository.reorderExercises(program.id, sheetB.id, ids, { save: false }).ok && programRepository.getExercises(program.id, sheetB.id)[0].id === ids[0]);
  coachProgramUi.sheetId = sheetA.id; discardCoachDraft(program.id, sheetA.id);
  const rendered = coachBuilderHtml();
  check("tabella avanzata renderizzata", rendered.includes("Carico prescritto") && rendered.includes('data-exercise-action="details"') && rendered.includes("RIR / RPE"));
  check("azioni multiple presenti", rendered.includes('data-exercise-toolbar="undo"') && rendered.includes("data-builder-add-row"));
  check("mobile card CSS", ${JSON.stringify(html.includes('@media (max-width: 430px)') && html.includes('.phase4-exercise-table tr.phase4-exercise-row'))});
  check("log allenamenti intatto", state.training.history[0].id === "log-intatto");
  const validation = programRepository.validate(); check("modello valido", validation.valid);
  return { ok: true, assertions, exercisesA: programRepository.getExercises(program.id, sheetA.id).length, exercisesB: programRepository.getExercises(program.id, sheetB.id).length };
})()`, context);

console.log(JSON.stringify(result, null, 2));
