import fs from "node:fs/promises";
import vm from "node:vm";
const html = await fs.readFile(new URL("../index.html", import.meta.url), "utf8");
const start = html.lastIndexOf("<script>") + 8, end = html.lastIndexOf("</script>");
const script = html.slice(start, end).replace(/\s+initFirebase\(\);\s+render\(\);\s*$/, "");
const storage = new Map(); const localStorage = { getItem:k=>storage.get(k)??null, setItem:(k,v)=>storage.set(k,String(v)), removeItem:k=>storage.delete(k) };
const el={addEventListener(){},querySelector(){return null;},querySelectorAll(){return[];},classList:{add(){},remove(){},toggle(){}},style:{},dataset:{}}; const document={getElementById(){return el;},querySelector(){return null;},querySelectorAll(){return[];},createElement(){return {...el};},body:el,documentElement:el,addEventListener(){}};
const context={console,structuredClone,Date,Math,JSON,Intl,Map,Set,WeakMap,Array,Object,String,Number,Boolean,RegExp,Promise,parseInt,parseFloat,isNaN,localStorage,sessionStorage:localStorage,document,navigator:{},location:{protocol:"file:",origin:"null",hash:""},URL:{createObjectURL(){return "blob:test";},revokeObjectURL(){}},Blob:class{},FileReader:class{},setTimeout(){return 1;},clearTimeout(){},requestAnimationFrame(){return 1;},addEventListener(){},removeEventListener(){},postMessage(){},window:null,globalThis:null}; context.window=context; context.globalThis=context; vm.createContext(context); new vm.Script(script).runInContext(context);
const result=vm.runInContext(`(() => { state=clone(baseState); state.programs=[]; state.training.sessions=[]; const p=programRepository.createProgram({id:"phase8-program",name:"Bikini Pro",durationWeeks:8,sheets:[]},{save:false}).value; const s=programRepository.createSheet(p.id,{id:"phase8-sheet",code:"A",name:"Lower Body",focus:"Glutei"},{save:false}).value; ["Abductor Machine","Cable Hip Abduction","Hip Abduction Machine","Standing Hip Abduction","Seated Hip Abduction"].forEach((name,i)=>programRepository.createExercise(p.id,s.id,{id:"phase8-ex-"+i,name,muscle:"Glutei",metadata:{pattern:"isolation",equipment:"macchina"},prescription:{sets:3,reps:"10-15",rir:"1-2",rest:{seconds:90}}},{save:false})); coachProgramUi.programId=p.id; coachProgramUi.sheetId=s.id; const suggestions=coachAiSuggestions(); coachProgramUi.aiExpanded.add(suggestions[0].id); const panel=coachAiPanelHtml(); const pop=coachAiPopupHtml(); const text=(panel+pop).replace(/<[^>]+>/g, " "); return {ok:true,checks:{grouped:suggestions.some(s=>s.involvedExercises?.length===5),names:["Abductor Machine","Cable Hip Abduction","Hip Abduction Machine","Standing Hip Abduction","Seated Hip Abduction"].every(n=>panel.includes(n)),compact:panel.includes("Apri dettagli"),tabs:["Suggerimenti","Applicati","Ignorati"].every(n=>panel.includes(n)),count:panel.includes("coach-ai-count"),robot:pop.includes("Ciao Alice")&&pop.includes("Vedi suggerimenti"),technicalIds:!text.includes("phase8-program")&&!text.includes("phase8-sheet")&&!text.includes("phase8-ex-")}}})()`,context); console.log(JSON.stringify(result,null,2));
