import fs from "node:fs/promises";
import vm from "node:vm";
const html=await fs.readFile(new URL("../index.html",import.meta.url),"utf8");
const script=html.slice(html.lastIndexOf("<script>")+8,html.lastIndexOf("</script>")).replace(/\s+initFirebase\(\);\s+render\(\);\s*$/,'');
const store=new Map(); const localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)}; const el={addEventListener(){},querySelector(){return null},querySelectorAll(){return[]},classList:{add(){},remove(){},toggle(){}},style:{},dataset:{}}; const document={getElementById(){return el},querySelector(){return null},querySelectorAll(){return[]},createElement(){return {...el}},body:el,documentElement:el,addEventListener(){}};
const context={console,structuredClone,Date,Math,JSON,Intl,Map,Set,WeakMap,Array,Object,String,Number,Boolean,RegExp,Promise,parseInt,parseFloat,isNaN,localStorage,sessionStorage:localStorage,document,navigator:{},location:{protocol:"file:",origin:"null",hash:""},URL:{createObjectURL(){return "blob:test"},revokeObjectURL(){}},Blob:class{},FileReader:class{},setTimeout(){return 1},clearTimeout(){},requestAnimationFrame(){return 1},addEventListener(){},removeEventListener(){},window:null,globalThis:null}; context.window=context; context.globalThis=context; vm.createContext(context); new vm.Script(script).runInContext(context);
const result=vm.runInContext(`(() => { const sheets=Array.from({length:8},(_,i)=>({id:"s"+(i+1),code:"B1-A"+(i+1),letter:"A",week:i+1,name:"Scheda A"+(i+1),phase:"B program 1",exercises:[{id:"e"+i,name:"Hip_Thrust",muscle:"Glutei",sets:String(i===7?1:3),reps:i===0?"15":i===1?"12":i===2?"10":i===3?"10":i===7?"Test 8 RM":"10",rir:"",rest:"2'",tempo:"3 sec",note:"nota"}]})); const input={meta:{schemaVersion:2},programs:[{id:"p",name:"B program 1",phase:"B program 1",durationWeeks:8,sheets}]}; const out=runSchemaMigrations(input,3); const p=out.state.programs[0], s=p.sheets[0], e=s.exercises[0]; if(!out.ok||s.code!=="A"||e.progression.weeks.length!==8||e.progression.weeks[7].type!=="test"||!p.archivedSheets?.length||!localStorage.getItem(PRE_WEEK_CONSOLIDATION_BACKUP_KEY)) throw new Error("consolidamento non valido"); return {ok:true,logicalSheets:p.sheets.length,weeks:e.progression.weeks.length,archived:p.archivedSheets.length,backup:true}; })()`,context); console.log(JSON.stringify(result,null,2));

const real=vm.runInContext(`(() => { const programs=buildProgramsFromLegacy(PROGRAM_LIBRARY,[]); const source=programs.find((program)=>String(program.phase).toLowerCase()==="b program 1"); if(!source) throw new Error("B program 1 non presente nella libreria reale"); const repaired=consolidateLegacyWeeklyProgram(source); const sheet=repaired.sheets.find((item)=>item.code==="A"); const exercise=sheet.exercises.find((item)=>normalizeExerciseName(item.name).includes("hip thrust")); if(!exercise) throw new Error("Hip Thrust non presente nella scheda A reale"); const weeks=exercise.progression.weeks.map((week)=>({sets:Number(week.sets),reps:week.reps?.label||"",type:week.type})); const expected=[{sets:3,reps:"15",type:"normal"},{sets:3,reps:"12",type:"normal"},{sets:3,reps:"10",type:"normal"},{sets:2,reps:"10",type:"normal"},{sets:4,reps:"10",type:"normal"},{sets:4,reps:"10",type:"normal"},{sets:2,reps:"8",type:"normal"},{sets:1,reps:"Test 8 RM",type:"test"}]; if(JSON.stringify(weeks)!==JSON.stringify(expected)) throw new Error("Hip Thrust B1/A S1-S8 non coincide con i dati reali: "+JSON.stringify(weeks)); return {ok:true,sourceSheets:source.sheets.length,logicalSheets:repaired.sheets.length,weeks}; })()`,context); console.log(JSON.stringify(real,null,2));
